
#Tier Config. This config is synced from server to client.
[tier]

	#Items
	[tier.Items]

		#QIO Drivers
		[tier.Items.qio_drivers]
			#The number of items that the Absolute QIO Drive can store.
			#Range: 1 ~ 9223372036854775807
			absoluteCount = 128000000000
			#The number of types that the Absolute QIO Drive can store.
			#Range: > 1
			absoluteTypes = 16384
			#The number of items that the Supreme QIO Drive can store.
			#Range: 1 ~ 9223372036854775807
			supremeCount = 1048000000000
			#The number of types that the Supreme QIO Drive can store.
			#Range: > 1
			supremeTypes = 65536
			#The number of items that the Cosmic QIO Drive can store.
			#Range: 1 ~ 9223372036854775807
			cosmicCount = 8000000000000
			#The number of types that the Cosmic QIO Drive can store.
			#Range: > 1
			cosmicTypes = 262144
			#The number of items that the Infinite QIO Drive can store.
			#Range: 1 ~ 9223372036854775807
			infiniteCount = 16000000000000
			#The number of types that the Infinite QIO Drive can store.
			#Range: > 1
			infiniteTypes = 1048576

	#Storages
	[tier.Storages]

		#Bins
		[tier.Storages.bins]
			#The number of items Absolute bins can store.
			#Range: > 1
			absoluteStorage = 2097152
			#The number of items Supreme bins can store.
			#Range: > 1
			supremeStorage = 16777216
			#The number of items Cosmic bins can store.
			#Range: > 1
			cosmicStorage = 134217728
			#The number of items Infinite bins can store.
			#Range: > 1
			infiniteStorage = 1073741824

		#Induction
		[tier.Storages.induction]
			#Maximum number of Joules Absolute induction cells can store.
			absoluteStorage = "32768000000000"
			#Maximum number of Joules Supreme induction cells can store.
			supremeStorage = "262144000000000"
			#Maximum number of Joules Cosmic induction cells can store.
			cosmicStorage = "2097152000000000"
			#Maximum number of Joules Infinite induction cells can store.
			infiniteStorage = "9223372036854775807"
			#Maximum number of Joules Absolute induction providers can output or accept.
			absoluteOutput = "1048576000"
			#Maximum number of Joules Supreme induction providers can output or accept.
			supremeOutput = "8388608000"
			#Maximum number of Joules Cosmic induction providers can output or accept.
			cosmicOutput = "67108864000"
			#Maximum number of Joules Infinite induction providers can output or accept.
			infiniteOutput = "536870912000"

		#Energy Cubes
		[tier.Storages.energy_cubes]
			#Maximum number of Joules Absolute energy cubes can store.
			absoluteStorage = "1024000000"
			#Output rate in Joules of Absolute energy cubes.
			absoluteOutput = "1024000"
			#Maximum number of Joules Supreme energy cubes can store.
			supremeStorage = "4096000000"
			#Output rate in Joules of Supreme energy cubes.
			supremeOutput = "4096000"
			#Maximum number of Joules Cosmic energy cubes can store.
			cosmicStorage = "16384000000"
			#Output rate in Joules of Cosmic energy cubes.
			cosmicOutput = "16384000"
			#Maximum number of Joules Infinite energy cubes can store.
			infiniteStorage = "65536000000"
			#Output rate in Joules of Infinite energy cubes.
			infiniteOutput = "65536000"

		#Fluid Tanks
		[tier.Storages.fluid_tanks]
			#Storage size of Absolute fluid tanks in mB.
			#Range: > 1
			absoluteStorage = 4096000
			#Output rate of Absolute fluid tanks in mB.
			#Range: > 1
			absoluteOutput = 2048000
			#Storage size of Supreme fluid tanks in mB.
			#Range: > 1
			supremeStorage = 32768000
			#Output rate of Supreme fluid tanks in mB.
			#Range: > 1
			supremeOutput = 16384000
			#Storage size of Cosmic fluid tanks in mB.
			#Range: > 1
			cosmicStorage = 262144000
			#Output rate of Cosmic fluid tanks in mB.
			#Range: > 1
			cosmicOutput = 131072000
			#Storage size of Infinite fluid tanks in mB.
			#Range: > 1
			infiniteStorage = 2097152000
			#Output rate of Infinite fluid tanks in mB.
			#Range: > 1
			infiniteOutput = 1048576000

		#Chemical Tanks
		[tier.Storages.chemical_tanks]
			#Storage size of Absolute chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			absoluteStorage = 32768000
			#Output rate of Absolute chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			absoluteOutput = 2048000
			#Storage size of Supreme chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			supremeStorage = 131072000
			#Output rate of Supreme chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			supremeOutput = 8192000
			#Storage size of Cosmic chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			cosmicStorage = 524288000
			#Output rate of Cosmic chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			cosmicOutput = 32768000
			#Storage size of Infinite chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			infiniteStorage = 4194304000
			#Output rate of Infinite chemical tanks in mB.
			#Range: 1 ~ 9223372036854775807
			infiniteOutput = 131072000

		#Radioactive Barrel
		[tier.Storages.radioactive_waste_barrel]
			#Amount of gas (mB) that can be stored in Absolute Radioactive Waste Barrel.
			#Range: 1 ~ 9223372036854775807
			absoluteStorage = 2048000
			#Number of ticks required for radioactive gas stored in Absolute Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			#Range: > 1
			absoluteProcessTicks = 20
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Absolute Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			#Range: 0 ~ 9223372036854775807
			absoluteDecayAmount = 4
			#Amount of gas (mB) that can be stored in Supreme Radioactive Waste Barrel.
			#Range: 1 ~ 9223372036854775807
			supremeStorage = 8192000
			#Number of ticks required for radioactive gas stored in Supreme Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			#Range: > 1
			supremeProcessTicks = 10
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Supreme Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			#Range: 0 ~ 9223372036854775807
			supremeDecayAmount = 16
			#Amount of gas (mB) that can be stored in Cosmic Radioactive Waste Barrel.
			#Range: 1 ~ 9223372036854775807
			cosmicStorage = 32768000
			#Number of ticks required for radioactive gas stored in Cosmic Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			#Range: > 1
			cosmicProcessTicks = 5
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Cosmic Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			#Range: 0 ~ 9223372036854775807
			cosmicDecayAmount = 64
			#Amount of gas (mB) that can be stored in Infinite Radioactive Waste Barrel.
			#Range: 1 ~ 9223372036854775807
			infiniteStorage = 131072000
			#Number of ticks required for radioactive gas stored in Infinite Radioactive Waste Barrel to decay radioactiveWasteBarrelDecayAmount mB.
			#Range: > 1
			infiniteProcessTicks = 5
			#Number of mB of gas that decay every radioactiveWasteBarrelProcessTicks ticks when stored in Infinite Radioactive Waste Barrel. Set to zero to disable decay all together. (Gases in the mekanism:waste_barrel_decay_blacklist tag will not decay).
			#Range: 0 ~ 9223372036854775807
			infiniteDecayAmount = 256

	#Transmitters
	[tier.transmitters]

		#Universal Cables
		[tier.transmitters.energy]
			#Internal buffer in Joules of each absolute universal cable
			absoluteUniversalCable = "65536000"
			#Internal buffer in Joules of each supreme universal cable
			supremeUniversalCable = "524288000"
			#Internal buffer in Joules of each cosmic universal cable
			cosmicUniversalCable = "4194304000"
			#Internal buffer in Joules of each infinite universal cable
			infiniteUniversalCable = "33554432000"

		#Mechanical Pipes
		[tier.transmitters.fluid]
			#Capacity of absolute mechanical pipes in mB.
			absoluteMechanicalPipesCapacity = "512000"
			#Pump rate of absolute mechanical pipes in mB/t.
			absoluteMechanicalPipesPullAmount = "128000"
			#Capacity of supreme mechanical pipes in mB.
			supremeMechanicalPipesCapacity = "2048000"
			#Pump rate of supreme mechanical pipes in mB/t.
			supremeMechanicalPipesPullAmount = "512000"
			#Capacity of cosmic mechanical pipes in mB.
			cosmicMechanicalPipesCapacity = "8192000"
			#Pump rate of cosmic mechanical pipes in mB/t.
			cosmicMechanicalPipesPullAmount = "2048000"
			#Capacity of infinite mechanical pipes in mB.
			infiniteMechanicalPipesCapacity = "32768000"
			#Pump rate of infinite mechanical pipes in mB/t.
			infiniteMechanicalPipesPullAmount = "8192000"

		#Pressurized Tubes
		[tier.transmitters.chemical]
			#Capacity of absolute pressurized tubes in mB.
			absolutePressurizedTubesCapacity = "4096000"
			#Pump rate of absolute pressurized tubes in mB/t.
			absolutePressurizedTubesPullAmount = "1024000"
			#Capacity of supreme pressurized tubes in mB.
			supremePressurizedTubesCapacity = "16384000"
			#Pump rate of supreme pressurized tubes in mB/t.
			supremePressurizedTubesPullAmount = "4096000"
			#Capacity of cosmic pressurized tubes in mB.
			cosmicPressurizedTubesCapacity = "65536000"
			#Pump rate of cosmic pressurized tubes in mB/t.
			cosmicPressurizedTubesPullAmount = "16384000"
			#Capacity of infinite pressurized tubes in mB.
			infinitePressurizedTubesCapacity = "262144000"
			#Pump rate of infinite pressurized tubes in mB/t.
			infinitePressurizedTubesPullAmount = "65536000"

		#Logistical Transporters
		[tier.transmitters.item]
			#Five times the travel speed in m/s of absolute logistical transporter.
			absoluteLogisticalTransporterSpeed = "55"
			#Item throughput rate of absolute logistical transporters in items/half second.
			absoluteLogisticalTransporterPullAmount = "128"
			#Five times the travel speed in m/s of supreme logistical transporter.
			supremeLogisticalTransporterSpeed = "60"
			#Item throughput rate of supreme logistical transporters in items/half second.
			supremeLogisticalTransporterPullAmount = "256"
			#Five times the travel speed in m/s of cosmic logistical transporter.
			cosmicLogisticalTransporterSpeed = "70"
			#Item throughput rate of cosmic logistical transporters in items/half second.
			cosmicLogisticalTransporterPullAmount = "512"
			#Five times the travel speed in m/s of infinite logistical transporter.
			infiniteLogisticalTransporterSpeed = "100"
			#Item throughput rate of infinite logistical transporters in items/half second.
			infiniteLogisticalTransporterPullAmount = "1024"

		#Thermodynamic Conductors
		[tier.transmitters.heat]
			#Conduction value of absolute thermodynamic conductors.
			absoluteThermodynamicConductorConduction = "10"
			#Heat capacity of absolute thermodynamic conductors.
			absoluteThermodynamicConductornCapacity = "1"
			#Insulation value of absolute thermodynamic conductor.
			absoluteThermodynamicConductornInsulation = "400000"
			#Conduction value of supreme thermodynamic conductors.
			supremeThermodynamicConductorConduction = "15"
			#Heat capacity of supreme thermodynamic conductors.
			supremeThermodynamicConductornCapacity = "1"
			#Insulation value of supreme thermodynamic conductor.
			supremeThermodynamicConductornInsulation = "800000"
			#Conduction value of cosmic thermodynamic conductors.
			cosmicThermodynamicConductorConduction = "20"
			#Heat capacity of cosmic thermodynamic conductors.
			cosmicThermodynamicConductornCapacity = "1"
			#Insulation value of cosmic thermodynamic conductor.
			cosmicThermodynamicConductornInsulation = "1000000"
			#Conduction value of infinite thermodynamic conductors.
			infiniteThermodynamicConductorConduction = "25"
			#Heat capacity of infinite thermodynamic conductors.
			infiniteThermodynamicConductornCapacity = "1"
			#Insulation value of infinite thermodynamic conductor.
			infiniteThermodynamicConductornInsulation = "4000000"

